#!/bin/bash

set -e
set -u

function usage() {
    echo "$0 [options]"
    echo
    echo "Valid options:"
    echo
    echo " -h               what you are reading now"
    echo " -c cluster_name  make a cluster with this prefix"
    echo " -e extra_vars    set extra vars (passed to ansible as -e)"
    echo " -p profile       specify the provisioning profile to use (ex: simple, split)"
    echo "some useful extra_vars might be:"
    echo " -e swift_deployment_method=package - don't deploy from source"
    echo " -e rax_keypair=something - use YOUR keypair name, not mine"
    echo
}

PROV_DIR=$(dirname $0)/prov_templ

CLUSTER=c1
EXTRA_ARGS="-e @${PROV_DIR}/prov-vars.yml"
PROFILE=simple
OPTERR=1
while getopts "hc:e:p:" OPTION; do
    case ${OPTION} in
        h)
            usage
            exit 0
            ;;

        c)
            CLUSTER=${OPTARG}
            ;;

        e)
            EXTRA_ARGS="${EXTRA_ARGS} -e ${OPTARG}"
            ;;

        p)
            PROFILE=${OPTARG}
            if [ ! -e "${PROV_DIR}/${PROFILE}" ]; then
                print "Cannot find provisioning template: ${PROFILE}"
                exit 1
            fi
            ;;

        ?)
            usage
            exit 1
            ;;
    esac
done

for override in all ${PROFILE} ${CLUSTER}; do
    if [ -e local/${override}.json ]; then
        EXTRA_ARGS="-e @${override}.json ${EXTRA_ARGS}"
    fi
done

cmd="ansible-playbook provision.yml -i ${PROV_DIR}/${PROFILE} ${EXTRA_ARGS} -e prefix=${CLUSTER} -e profile=${PROFILE}"
echo "Running \"${cmd}\""
$cmd
