#!/bin/bash

set -e
set -u

function usage() {
    echo "$0 [options]"
    echo
    echo "Valid options:"
    echo
    echo " -h               what you are reading now"
    echo " -c cluster_name  make a cluster with this prefix"
    echo " -e extra_vars    set extra vars (passed to ansible as -e)"
    echo
    echo "some useful extra_vars might be:"
    echo " -e swift_deployment_method=package - don't deploy from source"
    echo " -e rax_keypair=something - use YOUR keypair name, not mine"
    echo
}

CLUSTER=c1
EXTRA_ARGS=""

while getopts "hc:e:" OPTION; do
    case ${OPTION} in
        h)
            usage
            exit 0
            ;;

        c)
            CLUSTER=${OPTARG}
            ;;

        e)
            EXTRA_ARGS="${EXTRA_ARGS} -e ${OPTARG}"
            ;;

        *)
            usage
            exit 1
            ;;
    esac
done

ansible-playbook provision.yml -e prefix=${CLUSTER} ${EXTRA_ARGS}
