#!/bin/bash

set -e
set -u

# optionally allow -c <cluster>
if [ "${1:-}" == "-c" ]; then
    shift
fi

CLUSTER=${1:-c1}

ansible-playbook deprovision.yml -l${CLUSTER}:localhost -e @prov_templ/prov-vars.yml -e prefix=${CLUSTER}
