#!/bin/bash

CONTAINER_PERCENT=$(sudo swift-dispersion-report --container-only 2>/dev/null | grep "copies found" | cut -d' ' -f1)
OBJECT_PERCENT=$(sudo swift-dispersion-report --object-only 2>/dev/null | grep "copies found" | cut -d' ' -f1)

if [ "${CONTAINER_PERCENT}" != "100.00%" ]; then
    echo PUTNOTIF host=$(hostname) time=$(date +%s) message=\"Container dispersion: ${CONTAINER_PERCENT}\" severity=failure
fi

if [ "${OBJECT_PERCENT}" != "100.00%" ]; then
    echo PUTNOTIF host=$(hostname) time=$(date +%s) message=\"Object dispersion: ${OBJECT_PERCENT}\" severity=failure
fi

echo PUTVAL "$(hostname)/swift-dispersion/gauge-container" interval=60 $(date +%s):$(echo ${CONTAINER_PERCENT} | sed -e s/%//)

echo PUTVAL "$(hostname)/swift-dispersion/gauge-object" interval=60 $(date +%s):$(echo ${OBJECT_PERCENT} | sed -e s/%//)

sleep 60





